config/routes.rb
Justjessy::Application.routes.draw do
  resources :recipes

  get "pages/info"
  root :to => redirect('/ideas')
  resources :ideas

  get "pages" => redirect('/pages/info')

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :string, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
		@recipes= Recipe.all 
	end

	def new
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.save
		redirect_to @recipe
	end

	private
	  	def recipe_params
			params.require(:recipe).permit(:course, :name, :ingredients, :duration, :description)
		end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>String</th>
      <th>Description</th>
      <th>Picture</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.string %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>String:</strong>
  <%= @idea.string %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @idea.picture %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Justjessy</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Just Jessy</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%=link_to "About me", pages_path%></li>
        <li><%=link_to "Recipes", recipes_path%></li>
        <li><%=link_to "Travel stories", ideas_path%></li>
      

      </ul>
    </div>
  </div>
</nav>
  <div class="container">
	 <%= yield %>
  </div>
  </body>
  <footer>
  <div class="container">
    Just Jessy 2014
  </div>
</footer>

</html>

app/views/pages/info.html.erb
<h1>About me</h1>
<p>I'm 'just' Jessy. Please look around on my just self-build website!</p>

app/views/recipes/_form.html.erb
<%= form_for :recipe, url: recipes_path do |f| %>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_field :ingredients %>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipe</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Name</th>
      <th>Ingredients</th>
      <th>Duration</th>
      <th>Description</th>
     </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.course %></td>
        <td><%= recipe.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.duration %></td>
        <td><%= recipe.description %></td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<%=@recipe.course%>
<%=@recipe.name%>
<%=@recipe.ingredients%>
<%=@recipe.duration%>
<%=@recipe.description%>